---
title: "PREDiCTOR Pilot Study: Participants' Qualitative Feedback Word Clouds"
author: "Debi Gonzalez"
date: "2025-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Setting up libraries
library(tidyverse)
library(readxl)
library(wordcloud)
library(RColorBrewer)
library(ggwordcloud)
library(ggplot2)

# Sinai-inspired palette
sinai_colors <- c("#007BC7",  # Sinai Blue
  "#C6007E",  # Sinai Magenta
  "#6C2DC7",  # Purple/Violet
  "#00B1B0",  # Teal
  "#5A5A5A")   # Neutral gray for balance (optional)

```

### Obsbot Setup Feedback
```{r obsbot, echo=FALSE}
obsbot_df <- read_excel("/Users/debigonzalez/Documents/R_Projects/Predictor_Pilot_Qual/obsbot_descriptor_frequencies.xlsx")


ggplot(obsbot_df, aes(label = Descriptor, size = Approximate_Mentions, color = sample(Descriptor))) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 20) +
  scale_color_manual(values = rep(sinai_colors, length.out = nrow(obsbot_df))) +
  theme_minimal()
```

### iPhone Setup Feedback
```{r iphone, echo=FALSE}
iphone_df <- read_excel("/Users/debigonzalez/Documents/R_Projects/Predictor_Pilot_Qual/single_iphone_descriptors.xlsx")

ggplot(iphone_df, aes(label = descriptors, size = approximate_frequency, color = sample(descriptors))) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 20) +
  scale_color_manual(values = rep(sinai_colors, length.out = nrow(iphone_df))) +
  theme_minimal()
  
```

### Dual iPhone Setup Feedback
```{r dual iphone, echo=FALSE}
dual_iphone_df <- read_excel("/Users/debigonzalez/Documents/R_Projects/Predictor_Pilot_Qual/dual_iphone_descriptors.xlsx")

ggplot(dual_iphone_df, aes(label = descriptors, size = approximate_frequency, color = sample(descriptors))) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 20) +
  scale_color_manual(values = rep(sinai_colors, length.out = nrow(dual_iphone_df))) +
  theme_minimal()
  
```

### Logitech Setup Feedback
```{r logi, echo=FALSE}
logi_df <- read_excel("/Users/debigonzalez/Documents/R_Projects/Predictor_Pilot_Qual/logitech_descriptors.xlsx")

ggplot(logi_df, aes(label = descriptors, size = approximate_frequency, color = sample(descriptors))) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 20) +
  scale_color_manual(values = rep(sinai_colors, length.out = nrow(logi_df))) +
  theme_minimal()
  
```

### 360 Camera Setup Feedback
```{r cam360, echo=FALSE}
cam360_df <- read_excel("/Users/debigonzalez/Documents/R_Projects/Predictor_Pilot_Qual/camera360_descriptors.xlsx")

ggplot(cam360_df, aes(label = descriptors, size = approximate_frequency, color = sample(descriptors))) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 20) +
  scale_color_manual(values = rep(sinai_colors, length.out = nrow(cam360_df))) +
  theme_minimal()
  
```